public class NM_CYFD_AssessmentWrapper{
    
    @AuraEnabled public Integer stepNumber;
    @AuraEnabled public String  IKnowAnAdultWhoWillGoWithMePERM{GET;SET;}
    @AuraEnabled public String  IKnowOneAdultWhoWouldTakeMyCall{GET;SET;}
    @AuraEnabled public String  IHaveOneTrustedAdultWhoWillVisit{GET;SET;}
    @AuraEnabled public String  IHaveFamilyToSpendTimeWithOnXMas{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoCouldCareForKids{GET;SET;}
    @AuraEnabled public String  IHaveInformationAboutMyFamily{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoICanGoToForHelp{GET;SET;}
    @AuraEnabled public String  ThereIsAtLeastOneAdultITrust{GET;SET;}
    @AuraEnabled public String  ICanGetInTouchWithAFamilyMember{GET;SET;}
    @AuraEnabled public String  IKnowAtLeastOneAdultIDependOn{GET;SET;}
    @AuraEnabled public String  IKnowWhatMyLegalPermanencyGoalIsPERM{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoWouldHelpMePERM{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultICanLiveWithForDays{GET;SET;}
    @AuraEnabled public String  ThereIsOneAdultIHaveContactWith{GET;SET;}
    @AuraEnabled public String  IHaveAnAdultInMyLifeWhoCares{GET;SET;}
    @AuraEnabled public String  AnAdultITrustChecksInWithMePERM{GET;SET;}
    @AuraEnabled public String  IAmAPartOfAFamilyAndWeCarePERM{GET;SET;}
    @AuraEnabled public String  ITalkedAnAdultWhoHasAJobILike{GET;SET;}
    @AuraEnabled public String  ITalkedAboutMyPlansWithAnAdult{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoWillHelpMeApplyPERM{GET;SET;}

    @AuraEnabled public String  IKnowWhereToGoForTheInternet{GET;SET;}
    @AuraEnabled public String  ICanFindWhatINeedOnTheInternet{GET;SET;}
    @AuraEnabled public String  IKnowHowToUseMyEmailAccount{GET;SET;}
    @AuraEnabled public String  IKnowTheProductsToUseWhenCleaning{GET;SET;}
    @AuraEnabled public String  IKnowHowToSendComputerDocuments{GET;SET;}
    @AuraEnabled public String  IfSomeoneSendMeMessagesIWillTell{GET;SET;}
    @AuraEnabled public String  IKnowOneAdultWhoWouldTakeMyCallDL{GET;SET;}
    @AuraEnabled public String  IUnderstandHowToReadFoodLabels{GET;SET;}
    @AuraEnabled public String  IKnowHowToDoMyOwnLaundry{GET;SET;}
    @AuraEnabled public String  IKnowHowToUseAFireExtinguisher{GET;SET;}
    @AuraEnabled public String  IKnowTheRisksMeetingPeopleOnline{GET;SET;}
    @AuraEnabled public String  IWouldNotPostPicturesOrMessages{GET;SET;}
    @AuraEnabled public String  ICanMakeMealsWithOrWithoutRecipes{GET;SET;}
    @AuraEnabled public String  IKeepMyLivingSpaceClean{GET;SET;}
    @AuraEnabled public String  AnAdultITrustChecksInWithMeDL{GET;SET;}
    @AuraEnabled public String  IThinkAboutWhatIEatAndItsImpact{GET;SET;}
    @AuraEnabled public String  WhenIShopForFoodITakeAList{GET;SET;}
            
    @AuraEnabled public String  IHaveOneTrustedAdultWhoWillVisitSC{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetAwayFromHarm{GET;SET;}
    @AuraEnabled public String  IKnowWaysToProtectMyselfFromSTDs{GET;SET;}
    @AuraEnabled public String  IKnowHowToPreventGettingPregnant{GET;SET;}
    @AuraEnabled public String  ICanTakeCareOfMyOwnMinorInjuries{GET;SET;}
    @AuraEnabled public String  IKnowWhenIShouldGoToTheER{GET;SET;}
    @AuraEnabled public String  ThereIsOneAdultITrustToSpeak{GET;SET;}
    @AuraEnabled public String  IBatheDaily{GET;SET;}
    @AuraEnabled public String  IBrushMyTeethDaily{GET;SET;}
    @AuraEnabled public String  IHaveAPlaceToGoWhenIFeelUnsafe{GET;SET;}
    @AuraEnabled public String  IKnowWhereToGoGetSexInformation{GET;SET;}
    @AuraEnabled public String  ICanGetMedicalAndDentalCare{GET;SET;}
    @AuraEnabled public String  IKnowMyFamilyMedicalHistory{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetBenefitsLikeSS{GET;SET;}
    @AuraEnabled public String  ICanTurnDownASexualAdvance{GET;SET;}
    @AuraEnabled public String  IKnowHowToMakeMyOwnAppointments{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetHealthInsurance{GET;SET;}
            
    @AuraEnabled public String  IKnowHowToShowRespectToPeople{GET;SET;}
    @AuraEnabled public String  IThinkAboutTheImpactOfMyChoices{GET;SET;}
    @AuraEnabled public String  ICanSpeakUpForMyself{GET;SET;}
    @AuraEnabled public String  ICanDescribeMyBiologicalIdentity{GET;SET;}
    @AuraEnabled public String  IHaveFriendsILikeToBeWith{GET;SET;}
    @AuraEnabled public String  IHaveFamilyToSpendTimeWithOnXMasRC{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoCouldCareForKidsRC{GET;SET;}
    @AuraEnabled public String  IKnowSignsOfAnAbusiveRelationships{GET;SET;}
    @AuraEnabled public String  IHaveInformationAboutMyFamilyRC{GET;SET;}
    @AuraEnabled public String  IDealWithAngerAndNotHurtOthers{GET;SET;}
    @AuraEnabled public String  IKnowHowToActInSocialSettings{GET;SET;}
    @AuraEnabled public String  ICanGetInTouchWithFamily{GET;SET;}
    @AuraEnabled public String  IKnowAtLeastOneAdultWhenIExit{GET;SET;}
    @AuraEnabled public String  MyRelationshipsAreFreeFromHitting{GET;SET;}
    @AuraEnabled public String  IKnowWhatMyLegalPermanencyGoalIsRC{GET;SET;}
    @AuraEnabled public String  IShowOthersThatICareAboutThem{GET;SET;}
    @AuraEnabled public String  IAmAPartOfAFamilyAndWeCareRC{GET;SET;}
    @AuraEnabled public String  ICanExplainSexualOrientation{GET;SET;}
            
    @AuraEnabled public String  IUseOnlineBankingToTrackMyMoney{GET;SET;}
    @AuraEnabled public String  IKnowTheGoodAndBadOfLoanStores{GET;SET;}
    @AuraEnabled public String  IKnowWhatHappensIfIGetCaught{GET;SET;}
    @AuraEnabled public String  IKnowHowToUsePublicTransportation{GET;SET;}
    @AuraEnabled public String  IKnowTheImportanceOfGoodCredit{GET;SET;}
    @AuraEnabled public String  IKnowHowToFindSafeCheapHousing{GET;SET;}
    @AuraEnabled public String  IKnowWhatCanHappenWithMyLease{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultICanGoToForHelp{GET;SET;}
    @AuraEnabled public String  IPlanForTheExpensesIPayEachMonth{GET;SET;}
    @AuraEnabled public String  ICanFigureOutCostsOfOwningACar{GET;SET;}
    @AuraEnabled public String  IUnderstandMakingPurchasesWithCards{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoWouldHelpMeHM{GET;SET;}
    @AuraEnabled public String  ICanFigureOutTheCostsToMove{GET;SET;}
    @AuraEnabled public String  IKnowHowToFillOutAnAptRentalApp{GET;SET;}
    @AuraEnabled public String  ICanExplainTheNeedForInsurance{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultICanLiveWith{GET;SET;}
    @AuraEnabled public String  ThereIsAtLeastOneAdultIContact{GET;SET;}
    @AuraEnabled public String  ICanExplainHowToGetALicense{GET;SET;}
    @AuraEnabled public String  IUnderstandHowInterestRatesWork{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetERHelpToPayBills{GET;SET;}
    @AuraEnabled public String  IKnowHowToBalanceMyBankAccount{GET;SET;}
    @AuraEnabled public String  IPutMoneyInMySavingsAccount{GET;SET;}
    @AuraEnabled public String  IKeepRecordsOfMoneyIAmPaid{GET;SET;}
            
    @AuraEnabled public String  IKnowAnAdultWhoWillGoWithMeWS{GET;SET;}
    @AuraEnabled public String  IKnowHowToPrepareForExams{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetHelpFromSchool{GET;SET;}
    @AuraEnabled public String  ICanTakeCriticismWithoutLosingTemper{GET;SET;}
    @AuraEnabled public String  IKnowWhereICanGetTutoringForHelp{GET;SET;}
    @AuraEnabled public String  ILookOverMyWorkForMistakes{GET;SET;}
    @AuraEnabled public String  IGetToSchoolOrWorkOnTime{GET;SET;}
    @AuraEnabled public String  IKnowHowToDevelopAResume{GET;SET;}
    @AuraEnabled public String  IKnowHowToFillOutAJobApp{GET;SET;}
    @AuraEnabled public String  IKnowHowToPrepareForJobInterview{GET;SET;}
    @AuraEnabled public String  IKnowWhyMyContactsHelpToFindWork{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetInfoINeedForWork{GET;SET;}
    @AuraEnabled public String  IKnowWhereToGetHelpWithTaxForms{GET;SET;}
    @AuraEnabled public String  AdultInMyLifeWhoCaresAboutSchool{GET;SET;}
    @AuraEnabled public String  IGetMyWorkDoneAndTurnedInOnTime{GET;SET;}
    @AuraEnabled public String  IKnowWhatInformationOnAPayStubIs{GET;SET;}
    @AuraEnabled public String  ICanFillOutAW_4PayrollExemption{GET;SET;}
    @AuraEnabled public String  IKnowWhatEmployeeBenefitsAre{GET;SET;}
    @AuraEnabled public String  IKnowWhatSexualDiscriminationIs{GET;SET;}
    @AuraEnabled public String  IKnowHowICanSeeMyJJSRecords{GET;SET;}
            
    @AuraEnabled public String  IKnowTheEducationINeedForWork{GET;SET;}
    @AuraEnabled public String  ICanExplainBenefitsOfVolunteerWork{GET;SET;}
    @AuraEnabled public String  ITalkedToAAdultWhoHasAJobIWant{GET;SET;}
    @AuraEnabled public String  IKnowHowToGetIntoJobAfterSchool{GET;SET;}
    @AuraEnabled public String  IHaveTalkedAboutMyEducationPlans{GET;SET;}
    @AuraEnabled public String  IKnowAnAdultWhoWillHelpMeApplyCE{GET;SET;}
    @AuraEnabled public String  IKnowHowToFindWorkInternships{GET;SET;}
    @AuraEnabled public String  IKnowWhereToFindInfoAboutTraining{GET;SET;}
    @AuraEnabled public String  IKnowHowToFindAidForEduation{GET;SET;}
            
    @AuraEnabled public String  IBelieveICanInfluenceLifeTurnOut{GET;SET;}
    @AuraEnabled public String  IBelieveRelationshipsHelpMeSucceed{GET;SET;}
    @AuraEnabled public String  MostDaysIAmProudOfLivingLife{GET;SET;}
    @AuraEnabled public String  IHaveARelationshipWithTrustedAdult{GET;SET;}
    @AuraEnabled public String  IWouldUseExperinceToHelpYouth{GET;SET;}
    @AuraEnabled public String  IFeelIAmReadyForNextPhaseOfLife{GET;SET;}
    @AuraEnabled public String  MostDaysIFeelIHaveControlOfLife{GET;SET;}
    @AuraEnabled public String  ICanDescribeMyVisionAsAnAdult{GET;SET;}
    
    public void  getPermanancy(Assessment__c assessment){
            System.debug('assessment in wrapper '+assessment);
            this.IKnowAnAdultWhoWillGoWithMePERM = assessment.I_know_an_adult_who_will_go_with_me__c;
            this.IKnowOneAdultWhoWouldTakeMyCall = assessment.I_know_one_adult_who_would_take_my_call__c ;
            this.IHaveOneTrustedAdultWhoWillVisit = assessment.I_have_one_trusted_adult_who_will_visit__c;
            this.IHaveFamilyToSpendTimeWithOnXMas = assessment.I_have_family_to_spend_time_with_on_XMas__c ;
            this.IKnowAnAdultWhoCouldCareForKids = assessment.I_know_an_adult_who_could_care_for_kids__c ;
            this.IHaveInformationAboutMyFamily = assessment.I_have_information_about_my_family__c ;
            this.IKnowAnAdultWhoICanGoToForHelp = assessment.I_know_an_adult_who_I_can_go_to_for_help__c ;
            this.ThereIsAtLeastOneAdultITrust = assessment.There_is_at_least_one_adult_I_trust__c ;
            this.ICanGetInTouchWithAFamilyMember = assessment.I_can_get_in_touch_with_a_family_member__c ;
            this.IKnowAtLeastOneAdultIDependOn= assessment.I_know_at_least_one_adult_I_depend_on__c ;
            this.IKnowWhatMyLegalPermanencyGoalIsPERM = assessment.I_know_what_my_legal_permanency_goal_is__c ;
            this.IKnowAnAdultWhoWouldHelpMePERM = assessment.I_know_an_adult_who_would_help_me__c;
            this.IKnowAnAdultICanLiveWithForDays = assessment.I_know_an_adult_I_can_live_with_for_days__c;
            this.ThereIsOneAdultIHaveContactWith = assessment.There_is_one_adult_I_have_contact_with__c;
            this.IHaveAnAdultInMyLifeWhoCares = assessment.I_have_an_adult_in_my_life_who_cares__c ;
            this.AnAdultITrustChecksInWithMePERM= assessment.An_adult_I_trust_checks_in_with_me__c;
            this.IAmAPartOfAFamilyAndWeCarePERM = assessment.I_am_a_part_of_a_family_and_we_care__c;
            this.ITalkedAnAdultWhoHasAJobILike = assessment.I_talked_an_adult_who_has_a_job_I_like__c ;
            this.ITalkedAboutMyPlansWithAnAdult = assessment.I_talked_about_my_plans_with_an_adult__c ;
            this.IKnowAnAdultWhoWillHelpMeApplyPERM = assessment.I_know_an_adult_who_will_help_me_apply__c ;
                    
          //return wrapper;
    }
    
    
    public Assessment__c savePermanancy(Assessment__c assessment){
        
        
        assessment.I_know_an_adult_who_will_go_with_me__c       = this.IKnowAnAdultWhoWillGoWithMePERM;
        assessment.I_know_one_adult_who_would_take_my_call__c   = this.IKnowOneAdultWhoWouldTakeMyCall;
        assessment.I_have_one_trusted_adult_who_will_visit__c   = this.IHaveOneTrustedAdultWhoWillVisit;
        assessment.I_have_family_to_spend_time_with_on_XMas__c  = this.IHaveFamilyToSpendTimeWithOnXMas;
        assessment.I_know_an_adult_who_could_care_for_kids__c   = this.IKnowAnAdultWhoCouldCareForKids;
        assessment.I_have_information_about_my_family__c        = this.IHaveInformationAboutMyFamily;
        assessment.I_know_an_adult_who_I_can_go_to_for_help__c  = this.IKnowAnAdultWhoICanGoToForHelp;
        assessment.There_is_at_least_one_adult_I_trust__c       = this.ThereIsAtLeastOneAdultITrust;
        assessment.I_can_get_in_touch_with_a_family_member__c   = this.ICanGetInTouchWithAFamilyMember;
        assessment.I_know_at_least_one_adult_I_depend_on__c     = this.IKnowAtLeastOneAdultIDependOn;
        assessment.I_know_what_my_legal_permanency_goal_is__c   = this.IKnowWhatMyLegalPermanencyGoalIsPERM;
        assessment.I_know_an_adult_who_would_help_me__c         = this.IKnowAnAdultWhoWouldHelpMePERM;
        assessment.I_know_an_adult_I_can_live_with_for_days__c  = this.IKnowAnAdultICanLiveWithForDays;
        assessment.There_is_one_adult_I_have_contact_with__c    = this.ThereIsOneAdultIHaveContactWith;
        assessment.I_have_an_adult_in_my_life_who_cares__c      = this.IHaveAnAdultInMyLifeWhoCares;
        assessment.An_adult_I_trust_checks_in_with_me__c        = this.AnAdultITrustChecksInWithMePERM;
        assessment.I_am_a_part_of_a_family_and_we_care__c       = this.IAmAPartOfAFamilyAndWeCarePERM;
        assessment.I_talked_an_adult_who_has_a_job_I_like__c    = this.ITalkedAnAdultWhoHasAJobILike;
        assessment.I_talked_about_my_plans_with_an_adult__c     = this.ITalkedAboutMyPlansWithAnAdult;
        assessment.I_know_an_adult_who_will_help_me_apply__c    = this.IKnowAnAdultWhoWillHelpMeApplyPERM;
        return assessment;
        
    }
    
    
    public void  getDailyLiving(Assessment__c assessment){
        
        
        this.IKnowWhereToGoForTheInternet = assessment.I_know_where_to_go_for_the_internet__c;
        this.ICanFindWhatINeedOnTheInternet = assessment.I_can_find_what_I_need_on_the_internet__c ;
        this.IKnowHowToUseMyEmailAccount = assessment.I_know_how_to_use_my_email_account__c;
        this.IKnowTheProductsToUseWhenCleaning = assessment.I_know_the_products_to_use_when_cleaning__c ;
        this.IKnowHowToSendComputerDocuments = assessment.I_know_how_to_send_computer_documents__c ;
        this.IfSomeoneSendMeMessagesIWillTell = assessment.If_someone_send_me_messages_I_ll_tell__c ;
        this.IKnowOneAdultWhoWouldTakeMyCallDL = assessment.I_know_an_adult_who_can_take_my_call_DL__c;
        this.IUnderstandHowToReadFoodLabels = assessment.I_understand_how_to_read_food_labels__c ;
        this.IKnowHowToDoMyOwnLaundry = assessment.I_know_how_to_do_my_own_laundry__c ;
        this.IKnowHowToUseAFireExtinguisher = assessment.I_know_how_to_use_a_fire_extinguisher__c ;
        this.IKnowTheRisksMeetingPeopleOnline= assessment.I_know_the_risks_meeting_people_online__c ;
        this.IWouldNotPostPicturesOrMessages = assessment.I_would_not_post_pictures_or_messages__c ;
        this.ICanMakeMealsWithOrWithoutRecipes = assessment.I_can_make_meals_with_or_without_recipes__c;
        this.IKeepMyLivingSpaceClean = assessment.I_keep_my_living_space_clean__c;
        this.AnAdultITrustChecksInWithMeDL = assessment.An_adult_I_trust_checks_in_with_me_DL__c;
        this.IThinkAboutWhatIEatAndItsImpact = assessment.I_think_about_what_I_eat_and_its_impact__c ;
        this.WhenIShopForFoodITakeAList = assessment.When_I_shop_for_food_I_take_a_list__c ;
        
          
    }
    public Assessment__c saveDailyLiving(Assessment__c assessment){
        
        
        assessment.I_know_where_to_go_for_the_internet__c = this.IKnowWhereToGoForTheInternet    ;
        assessment.I_can_find_what_I_need_on_the_internet__c = this.ICanFindWhatINeedOnTheInternet ;
        assessment.I_know_how_to_use_my_email_account__c = this.IKnowHowToUseMyEmailAccount   ;
        assessment.I_know_the_products_to_use_when_cleaning__c = this.IKnowTheProductsToUseWhenCleaning   ;
        assessment.I_know_how_to_send_computer_documents__c = this.IKnowHowToSendComputerDocuments ;
        assessment.If_someone_send_me_messages_I_ll_tell__c = this.IfSomeoneSendMeMessagesIWillTell ;
    	assessment.I_know_an_adult_who_can_take_my_call_DL__c = this.IKnowOneAdultWhoWouldTakeMyCallDL;
        assessment.I_understand_how_to_read_food_labels__c = this.IUnderstandHowToReadFoodLabels  ;
        assessment.I_know_how_to_do_my_own_laundry__c = this.IKnowHowToDoMyOwnLaundry  ;
        assessment.I_know_how_to_use_a_fire_extinguisher__c = this.IKnowHowToUseAFireExtinguisher ;
        assessment.I_know_the_risks_meeting_people_online__c = this.IKnowTheRisksMeetingPeopleOnline    ;
        assessment.I_would_not_post_pictures_or_messages__c = this.IWouldNotPostPicturesOrMessages ;
        assessment.I_can_make_meals_with_or_without_recipes__c = this.ICanMakeMealsWithOrWithoutRecipes   ;
        assessment.I_keep_my_living_space_clean__c = this.IKeepMyLivingSpaceClean   ;
      //  @AuraEnabled public String  AnAdultITrust,ChecksInWithMe    ;
        assessment.An_adult_I_trust_checks_in_with_me_DL__c  = this.AnAdultITrustChecksInWithMeDL;
        assessment.I_think_about_what_I_eat_and_its_impact__c = this.IThinkAboutWhatIEatAndItsImpact ;
        assessment.When_I_shop_for_food_I_take_a_list__c = this.WhenIShopForFoodITakeAList ;
        return assessment;
        
    }
    
    
    public void  getSelfCare(Assessment__c assessment){
        
        
    	this.IHaveOneTrustedAdultWhoWillVisitSC = assessment.IHaveOneTrustedAdultWhoWillVisit_SC__c   ;
        this.IKnowHowToGetAwayFromHarm = assessment.I_know_how_to_get_away_from_harm__c;
        this.IKnowWaysToProtectMyselfFromSTDs = assessment.I_know_ways_to_protect_myself_from_STDs__c ;
        this.IKnowHowToPreventGettingPregnant = assessment.I_know_how_to_prevent_getting_pregnant__c;
        this.ICanTakeCareOfMyOwnMinorInjuries = assessment.I_can_take_care_of_my_own_minor_injuries__c ;
        this.IKnowWhenIShouldGoToTheER = assessment.I_know_when_I_should_go_to_the_ER__c ;
        this.ThereIsOneAdultITrustToSpeak = assessment.There_is_one_adult_I_trust_to_speak__c ;
        this.IBatheDaily = assessment.I_bathe_wash_up_daily__c ;
        this.IBrushMyTeethDaily = assessment.I_brush_my_teeth_daily__c ;
        this.IHaveAPlaceToGoWhenIFeelUnsafe = assessment.I_have_a_place_to_go_when_I_feel_unsafe__c ;
        this.IKnowWhereToGoGetSexInformation= assessment.I_know_where_to_go_get_sex_information__c ;
        this.ICanGetMedicalAndDentalCare = assessment.I_can_get_medical_and_dental_care__c ;
        this.IKnowMyFamilyMedicalHistory = assessment.I_know_my_family_medical_history__c;
        this.IKnowHowToGetBenefitsLikeSS = assessment.I_know_how_to_get_benefits_like_SS__c;
        this.ICanTurnDownASexualAdvance = assessment.I_can_turn_down_a_sexual_advance__c;
        this.IKnowHowToMakeMyOwnAppointments = assessment.I_know_how_to_make_my_own_appointments__c ;
        this.IKnowHowToGetHealthInsurance= assessment.I_know_how_to_get_health_insurance__c;
    }
    
    public Assessment__c saveSelfCare(Assessment__c assessment){
        
          assessment.IHaveOneTrustedAdultWhoWillVisit_SC__c   = this.IHaveOneTrustedAdultWhoWillVisitSC;
        
          assessment.I_know_how_to_get_away_from_harm__c = this.IKnowHowToGetAwayFromHarm   ;
          assessment.I_know_ways_to_protect_myself_from_STDs__c = this.IKnowWaysToProtectMyselfFromSTDs    ;
          assessment.I_know_how_to_prevent_getting_pregnant__c = this.IKnowHowToPreventGettingPregnant    ;
          assessment.I_can_take_care_of_my_own_minor_injuries__c = this.ICanTakeCareOfMyOwnMinorInjuries    ;
          assessment.I_know_when_I_should_go_to_the_ER__c = this.IKnowWhenIShouldGoToTheER   ;
          assessment.There_is_one_adult_I_trust_to_speak__c = this.ThereIsOneAdultITrustToSpeak    ;
          assessment.I_bathe_wash_up_daily__c = this.IBatheDaily   ;
          assessment.I_brush_my_teeth_daily__c = this.IBrushMyTeethDaily;
          assessment.I_have_a_place_to_go_when_I_feel_unsafe__c = this.IHaveAPlaceToGoWhenIFeelUnsafe  ;
          assessment.I_know_where_to_go_get_sex_information__c = this.IKnowWhereToGoGetSexInformation ;
          assessment.I_can_get_medical_and_dental_care__c = this.ICanGetMedicalAndDentalCare ;
          assessment.I_know_my_family_medical_history__c = this.IKnowMyFamilyMedicalHistory   ;
          assessment.I_know_how_to_get_benefits_like_SS__c = this.IKnowHowToGetBenefitsLikeSS ;
          assessment.I_can_turn_down_a_sexual_advance__c = this.ICanTurnDownASexualAdvance;
          assessment.I_know_how_to_make_my_own_appointments__c = this.IKnowHowToMakeMyOwnAppointments ;
          assessment.I_know_how_to_get_health_insurance__c = this.IKnowHowToGetHealthInsurance    ;
          return assessment;
    }

    public void  getRelations(Assessment__c assessment){
            
        
        this.IKnowHowToShowRespectToPeople = assessment.I_know_how_to_show_respect_to_people__c;
        this.IThinkAboutTheImpactOfMyChoices = assessment.I_think_about_the_impact_of_my_choices__c ;
        this.ICanSpeakUpForMyself = assessment.I_can_speak_up_for_myself__c;
        this.ICanDescribeMyBiologicalIdentity = assessment.I_can_describe_my_biological_identity__c ;
        this.IHaveFriendsILikeToBeWith = assessment.I_have_friends_I_like_to_be_with__c ;
        this.IHaveFamilyToSpendTimeWithOnXMasRC = assessment.I_have_family_to_be_with_on_XMas_RC__c	 ;
        this.IKnowAnAdultWhoCouldCareForKidsRC = assessment.An_adult_who_could_care_for_kids_RC__c  ;
        this.IHaveInformationAboutMyFamilyRC = assessment.I_have_information_about_my_family_RC__c 	;
        this.IKnowSignsOfAnAbusiveRelationships = assessment.I_know_signs_of_an_abusive_relationships__c ;
        this.IDealWithAngerAndNotHurtOthers = assessment.I_deal_with_anger_and_not_hurt_others__c ;
        this.IKnowHowToActInSocialSettings = assessment.I_know_how_to_act_in_social_settings__c ;
        this.ICanGetInTouchWithFamily = assessment.I_can_get_in_touch_with_family__c ;
        this.IKnowAtLeastOneAdultWhenIExit= assessment.I_know_at_least_one_adult_when_I_exit__c ;
        this.MyRelationshipsAreFreeFromHitting = assessment.My_relationships_are_free_from_hitting__c ;
        this.IKnowWhatMyLegalPermanencyGoalIsRC = assessment.I_understand_legal_permanency_goals_RC__c	;
        this.IShowOthersThatICareAboutThem = assessment.I_show_others_that_I_care_about_them__c;
        this.IAmAPartOfAFamilyAndWeCareRC = assessment.I_m_a_member_of_a_family_and_we_care_RC__c; 
        this.ICanExplainSexualOrientation = assessment.I_can_explain_sexual_orientation__c;
    }    
    public Assessment__c saveRelations(Assessment__c assessment){
        
        assessment.I_know_how_to_show_respect_to_people__c = this.IKnowHowToShowRespectToPeople   ;
        assessment.I_think_about_the_impact_of_my_choices__c = this.IThinkAboutTheImpactOfMyChoices ;
        assessment.I_can_speak_up_for_myself__c = this.ICanSpeakUpForMyself  ;
        assessment.I_can_describe_my_biological_identity__c = this.ICanDescribeMyBiologicalIdentity    ;
        assessment.I_have_friends_I_like_to_be_with__c = this.IHaveFriendsILikeToBeWith   ;
        assessment.I_have_family_to_be_with_on_XMas_RC__c	 = this.IHaveFamilyToSpendTimeWithOnXMasRC;
        assessment.An_adult_who_could_care_for_kids_RC__c  = this.IKnowAnAdultWhoCouldCareForKidsRC;
        assessment.I_have_information_about_my_family_RC__c  =  this.IHaveInformationAboutMyFamilyRC;
        assessment.I_know_signs_of_an_abusive_relationships__c = this.IKnowSignsOfAnAbusiveRelationships  ;
        assessment.I_deal_with_anger_and_not_hurt_others__c =  this.IDealWithAngerAndNotHurtOthers  ;   
        assessment.I_know_how_to_act_in_social_settings__c = this.IKnowHowToActInSocialSettings   ;
        assessment.I_can_get_in_touch_with_family__c = this.ICanGetInTouchWithFamily    ;
        assessment.I_know_at_least_one_adult_when_I_exit__c = this.IKnowAtLeastOneAdultWhenIExit   ;
        assessment.My_relationships_are_free_from_hitting__c = this.MyRelationshipsAreFreeFromHitting   ;
        assessment.I_understand_legal_permanency_goals_RC__c = this.IKnowWhatMyLegalPermanencyGoalIsRC;
        assessment.I_show_others_that_I_care_about_them__c = this.IShowOthersThatICareAboutThem ;
        assessment.I_m_a_member_of_a_family_and_we_care_RC__c = this.IAmAPartOfAFamilyAndWeCareRC;
        assessment.I_can_explain_sexual_orientation__c = this.ICanExplainSexualOrientation    ;
        return assessment;
        
    }
    
    
    
    public void  getHousing(Assessment__c assessment){
            this.IUseOnlineBankingToTrackMyMoney = assessment.I_use_online_banking_to_track_my_money__c;
            this.IKnowTheGoodAndBadOfLoanStores = assessment.I_know_the_good_and_bad_of_loan_stores__c ;
            this.IKnowWhatHappensIfIGetCaught = assessment.I_know_what_happens_if_I_get_caught__c;
            this.IKnowHowToUsePublicTransportation = assessment.I_know_how_to_use_public_transportation__c ;
            this.IKnowTheImportanceOfGoodCredit = assessment.I_know_the_importance_of_good_credit__c ;
            this.IKnowHowToFindSafeCheapHousing = assessment.I_know_how_to_find_safe_cheap_housing__c ;
            this.IKnowWhatCanHappenWithMyLease = assessment.I_know_what_can_happen_with_my_lease__c ;
            this.IKnowAnAdultICanGoToForHelp = assessment.I_know_an_adult_I_can_go_to_for_help__c ;
            this.IPlanForTheExpensesIPayEachMonth = assessment.I_plan_for_the_expenses_I_pay_each_month__c ;
            this.ICanFigureOutCostsOfOwningACar= assessment.I_can_figure_out_costs_of_owning_a_car__c ;
            this.IUnderstandMakingPurchasesWithCards = assessment.I_understand_making_purchases_with_cards__c ;
        	this.IKnowAnAdultWhoWouldHelpMeHM = assessment.I_know_an_adult_who_would_help_me_HM__c ;
            this.ICanFigureOutTheCostsToMove = assessment.I_can_figure_out_the_costs_to_move__c;
            this.IKnowHowToFillOutAnAptRentalApp = assessment.I_know_how_to_fill_out_an_apt_rental_app__c;
            this.ICanExplainTheNeedForInsurance = assessment.I_can_explain_the_need_for_insurance__c;
            this.IKnowAnAdultICanLiveWith = assessment.I_know_an_adult_I_can_live_with__c ;
            this.ThereIsAtLeastOneAdultIContact= assessment.There_is_at_least_one_adult_I_contact__c;
            this.ICanExplainHowToGetALicense = assessment.I_can_explain_how_to_get_a_license__c;
            this.IUnderstandHowInterestRatesWork = assessment.I_understand_how_interest_rates_work__c ;
            this.IKnowHowToGetERHelpToPayBills = assessment.I_know_how_to_get_ER_help_to_pay_bills__c ;
            this.IKnowHowToBalanceMyBankAccount = assessment.I_know_how_to_balance_my_bank_account__c ;
            this.IPutMoneyInMySavingsAccount = assessment.I_put_money_in_my_savings_account__c ;
            this.IKeepRecordsOfMoneyIAmPaid = assessment.I_keep_records_of_money_I_am_paid__c ;
        
          
    } 
    
    public Assessment__c saveHousing(Assessment__c assessment){
        
        assessment.I_use_online_banking_to_track_my_money__c = this.IUseOnlineBankingToTrackMyMoney ;
      assessment.I_know_the_good_and_bad_of_loan_stores__c = this.IKnowTheGoodAndBadOfLoanStores  ;
      assessment.I_know_what_happens_if_I_get_caught__c = this.IKnowWhatHappensIfIGetCaught    ;
      assessment.I_know_how_to_use_public_transportation__c = this.IKnowHowToUsePublicTransportation   ;
      assessment.I_know_the_importance_of_good_credit__c = this.IKnowTheImportanceOfGoodCredit  ;
      assessment.I_know_how_to_find_safe_cheap_housing__c = this.IKnowHowToFindSafeCheapHousing ;
      assessment.I_know_what_can_happen_with_my_lease__c = this.IKnowWhatCanHappenWithMyLease   ;
      assessment.I_know_an_adult_I_can_go_to_for_help__c = this.IKnowAnAdultICanGoToForHelp ;
      assessment.I_plan_for_the_expenses_I_pay_each_month__c = this.IPlanForTheExpensesIPayEachMonth    ;
      assessment.I_can_figure_out_costs_of_owning_a_car__c = this.ICanFigureOutCostsOfOwningACar  ;
      assessment.I_understand_making_purchases_with_cards__c = this.IUnderstandMakingPurchasesWithCards ;
        assessment.I_know_an_adult_who_would_help_me_HM__c = this.IKnowAnAdultWhoWouldHelpMeHM;
      assessment.I_can_figure_out_the_costs_to_move__c = this.ICanFigureOutTheCostsToMove ;
      assessment.I_know_how_to_fill_out_an_apt_rental_app__c = this.IKnowHowToFillOutAnAptRentalApp ;
      assessment.I_can_explain_the_need_for_insurance__c = this.ICanExplainTheNeedForInsurance  ;
      assessment.I_know_an_adult_I_can_live_with__c = this.IKnowAnAdultICanLiveWith    ;
      assessment.There_is_at_least_one_adult_I_contact__c = this.ThereIsAtLeastOneAdultIContact  ;
      assessment.I_can_explain_how_to_get_a_license__c = this.ICanExplainHowToGetALicense ;
      assessment.I_understand_how_interest_rates_work__c = this.IUnderstandHowInterestRatesWork ;
      assessment.I_know_how_to_get_ER_help_to_pay_bills__c = this.IKnowHowToGetERHelpToPayBills   ;
      assessment.I_know_how_to_balance_my_bank_account__c = this.IKnowHowToBalanceMyBankAccount ;
      assessment.I_put_money_in_my_savings_account__c = this.IPutMoneyInMySavingsAccount ;
      assessment.I_keep_records_of_money_I_am_paid__c = this.IKeepRecordsOfMoneyIAmPaid  ;
        
        return assessment;
    }
    
    
    
    public void  getWorkAndStudy(Assessment__c assessment){
        
        this.IKnowAnAdultWhoWillGoWithMeWS = assessment.I_know_an_adult_who_will_go_with_me_WS__c ;
        this.IKnowHowToPrepareForExams = assessment.I_know_how_to_prepare_for_exams__c;
        this.IKnowHowToGetHelpFromSchool = assessment.I_know_how_to_get_help_from_school__c ;
        this.ICanTakeCriticismWithoutLosingTemper = assessment.I_can_take_criticism_w_o_losing_temper__c;
        this.IKnowWhereICanGetTutoringForHelp = assessment.I_know_where_I_can_get_tutoring_for_help__c ;
        this.ILookOverMyWorkForMistakes = assessment.I_look_over_my_work_for_mistakes__c ;
        this.IGetToSchoolOrWorkOnTime = assessment.I_get_to_school_or_work_on_time__c ;
        this.IKnowHowToDevelopAResume = assessment.I_know_how_to_develop_a_resume__c ;
        this.IKnowHowToFillOutAJobApp = assessment.I_know_how_to_fill_out_a_job_app__c ;
        this.IKnowHowToPrepareForJobInterview = assessment.I_know_how_to_prepare_for_job_interview__c ;
        this.IKnowWhyMyContactsHelpToFindWork= assessment.I_know_why_my_contacts_help_to_find_work__c ;
        this.IKnowHowToGetInfoINeedForWork = assessment.I_know_how_to_get_info_I_need_for_work__c ;
        this.IKnowWhereToGetHelpWithTaxForms = assessment.I_know_where_to_get_help_with_tax_forms__c;
        this.AdultInMyLifeWhoCaresAboutSchool = assessment.Adult_in_my_life_who_cares_about_school__c;
        this.IGetMyWorkDoneAndTurnedInOnTime = assessment.I_get_my_work_done_and_turned_in_on_time__c;
        this.IKnowWhatInformationOnAPayStubIs = assessment.I_know_what_information_on_a_pay_stub_is__c ;
        this.ICanFillOutAW_4PayrollExemption= assessment.I_can_fill_out_a_W_4_payroll_exemption__c;
        this.IKnowWhatEmployeeBenefitsAre = assessment.I_know_what_employee_benefits_are__c;
        this.IKnowWhatSexualDiscriminationIs = assessment.I_know_what_sexual_discrimination_is__c ;
        this.IKnowHowICanSeeMyJJSRecords = assessment.I_know_how_I_can_see_my_JJS_records__c ;
    }
    
    public Assessment__c saveWorkAndStudy(Assessment__c assessment){
        
        assessment.I_know_an_adult_who_will_go_with_me_WS__c = this.IKnowAnAdultWhoWillGoWithMeWS;
       assessment.I_know_how_to_prepare_for_exams__c = this.IKnowHowToPrepareForExams   ;
      assessment.I_know_how_to_get_help_from_school__c = this.IKnowHowToGetHelpFromSchool ;
      assessment.I_can_take_criticism_w_o_losing_temper__c = this.ICanTakeCriticismWithoutLosingTemper    ;
      assessment.I_know_where_I_can_get_tutoring_for_help__c = this.IKnowWhereICanGetTutoringForHelp    ;
      assessment.I_look_over_my_work_for_mistakes__c = this.ILookOverMyWorkForMistakes ;
      assessment.I_get_to_school_or_work_on_time__c = this.IGetToSchoolOrWorkOnTime  ;
      assessment.I_know_how_to_develop_a_resume__c = this.IKnowHowToDevelopAResume ;
      assessment.I_know_how_to_fill_out_a_job_app__c = this.IKnowHowToFillOutAJobApp    ;
      assessment.I_know_how_to_prepare_for_job_interview__c = this.IKnowHowToPrepareForJobInterview    ;
      assessment.I_know_why_my_contacts_help_to_find_work__c = this.IKnowWhyMyContactsHelpToFindWork    ;
      assessment.I_know_how_to_get_info_I_need_for_work__c = this.IKnowHowToGetInfoINeedForWork   ;
      assessment.I_know_where_to_get_help_with_tax_forms__c = this.IKnowWhereToGetHelpWithTaxForms ;
      assessment.Adult_in_my_life_who_cares_about_school__c = this.AdultInMyLifeWhoCaresAboutSchool    ;
      assessment.I_get_my_work_done_and_turned_in_on_time__c = this.IGetMyWorkDoneAndTurnedInOnTime ;
      assessment.I_know_what_information_on_a_pay_stub_is__c = this.IKnowWhatInformationOnAPayStubIs    ;
      assessment.I_can_fill_out_a_W_4_payroll_exemption__c = this.ICanFillOutAW_4PayrollExemption ;
      assessment.I_know_what_employee_benefits_are__c = this.IKnowWhatEmployeeBenefitsAre  ;
      assessment.I_know_what_sexual_discrimination_is__c = this.IKnowWhatSexualDiscriminationIs ;
      assessment.I_know_how_I_can_see_my_JJS_records__c = this.IKnowHowICanSeeMyJJSRecords ;
        return assessment;
    }
    
    public void  getCareerAndEducation(Assessment__c assessment){
        
        this.IKnowAnAdultWhoWillHelpMeApplyCE =  assessment.I_know_adult_who_will_help_me_apply_CE__c ;
        this.IKnowTheEducationINeedForWork =  assessment.I_know_the_education_I_need_for_work__c  ;
        this.ICanExplainBenefitsOfVolunteerWork = assessment.I_can_explain_benefits_of_volunteer_work__c ;
        this.ITalkedToAAdultWhoHasAJobIWant = assessment.I_talked_to_a_adult_who_has_a_job_I_want__c;
        this.IKnowHowToGetIntoJobAfterSchool = assessment.I_know_how_to_get_into_job_after_school__c ;
        this.IHaveTalkedAboutMyEducationPlans = assessment.I_have_talked_about_my_education_plans__c ;
        this.IKnowAnAdultWhoWillHelpMeApplyCE = assessment.I_know_adult_who_will_help_me_apply_CE__c;
        this.IKnowHowToFindWorkInternships = assessment.I_know_how_to_find_work_internships__c ;
        this.IKnowWhereToFindInfoAboutTraining = assessment.I_know_where_to_find_info_about_training__c ;
        this.IKnowHowToFindAidForEduation = assessment.I_know_how_to_find_aid_for_eduation__c ;
         // return wrapper;
    }
    public Assessment__c saveCareerAndEducation(Assessment__c assessment){
        
        assessment.I_know_adult_who_will_help_me_apply_CE__c =  this.IKnowAnAdultWhoWillHelpMeApplyCE;
          assessment.I_know_the_education_I_need_for_work__c = this.IKnowTheEducationINeedForWork   ;
          assessment.I_can_explain_benefits_of_volunteer_work__c = this.ICanExplainBenefitsOfVolunteerWork  ;
          assessment.I_talked_to_a_adult_who_has_a_job_I_want__c = this.ITalkedToAAdultWhoHasAJobIWant  ;
          assessment.I_know_how_to_get_into_job_after_school__c = this.IKnowHowToGetIntoJobAfterSchool ;
          assessment.I_have_talked_about_my_education_plans__c = this.IHaveTalkedAboutMyEducationPlans    ;
          assessment.I_know_how_to_find_work_internships__c = this.IKnowHowToFindWorkInternships   ;
          assessment.I_know_where_to_find_info_about_training__c = this.IKnowWhereToFindInfoAboutTraining   ;
          assessment.I_know_how_to_find_aid_for_eduation__c = this.IKnowHowToFindAidForEduation    ;
          return assessment;
    }
    
    
    public void  getLookingForward(Assessment__c assessment){
         this.IBelieveICanInfluenceLifeTurnOut =  assessment.I_believe_I_can_influence_life_turn_out__c  ;
        this.IBelieveRelationshipsHelpMeSucceed = assessment.I_believe_relationships_help_me_succeed__c ;
        this.MostDaysIAmProudOfLivingLife = assessment.Most_days_I_am_proud_of_living_life__c;
        this.IHaveARelationshipWithTrustedAdult = assessment.I_have_a_relationship_with_trusted_adult__c ;
        this.IWouldUseExperinceToHelpYouth = assessment.I_would_use_experince_to_help_youth__c ;
        this.IFeelIAmReadyForNextPhaseOfLife = assessment.I_feel_I_am_ready_for_next_phase_of_life__c ;
        this.MostDaysIFeelIHaveControlOfLife = assessment.Most_days_I_feel_I_have_control_of_life__c ;
        this.ICanDescribeMyVisionAsAnAdult = assessment.I_can_describe_my_vision_as_an_adult__c ;
        
    }
    
    
    public Assessment__c saveLookingForward(Assessment__c assessment){
        
        
        assessment.I_believe_I_can_influence_life_turn_out__c = this.IBelieveICanInfluenceLifeTurnOut    ;
        assessment.I_believe_relationships_help_me_succeed__c = this.IBelieveRelationshipsHelpMeSucceed  ;
        assessment.Most_days_I_am_proud_of_living_life__c = this.MostDaysIAmProudOfLivingLife   ;
        assessment.I_have_a_relationship_with_trusted_adult__c = this.IHaveARelationshipWithTrustedAdult  ;
        assessment.I_would_use_experince_to_help_youth__c = this.IWouldUseExperinceToHelpYouth   ;
        assessment.I_feel_I_am_ready_for_next_phase_of_life__c = this.IFeelIAmReadyForNextPhaseOfLife ;
        assessment.Most_days_I_feel_I_have_control_of_life__c = this.MostDaysIFeelIHaveControlOfLife    ;
        assessment.I_can_describe_my_vision_as_an_adult__c = this.ICanDescribeMyVisionAsAnAdult   ;
        return assessment;
        
    }
    
}